from django.db import models


from .models.as_operation import as_operation
from .models.autosteer import autosteer
from .models.boat_detail import boat_detail
from .models.boat_driver import boat_driver
from .models.boat_info import boat_info 
from .models.call import call
from .models.conflict_log import conflict_log
from .models.contacts import contacts
from .models.course import course
from .models.course_set import course_set
from .models.course_survey_data import course_survey_data
from .models.device_sync_status import device_sync_status
from .models.driver_info import driver_info
from .models.file_format import file_format
from .models.gps_course import gps_course
from .models.group_invite import group_invite
from .models.health import health
from .models.log import log
from .models.media_file import media_file
from .models.media_folder import media_folder
from .models.media_in_folder import media_in_folder
from .models.media_layout_preset import media_layout_preset
from .models.media_tag import media_tag
from .models.mobile_detail import mobile_detail
from .models.mobile_permission_profile import mobile_permission_profile
from .models.mobile_template import mobile_template
from .models.onboarding_event import onboarding_event
from .models.reaction import reaction
from .models.rope_detail import rope_detail
from .models.rope import rope
from .models.set_detail import set_detail
from .models.set_log import set_log
from .models.share_link import share_link
from .models.shared_set import shared_set
from .models.shared_set_detail import shared_set_detail
from .models.ski_detail import ski_detail
from .models.ski_group import ski_group
from .models.skier_info import skier_info
from .models.speed import speed
from .models.stream import stream
from .models.sync_queue import sync_queue
from .models.tag import tag
from .models.template_element import template_element
from .models.ui_event_log import ui_event_log
from .models.ui_settings import ui_settings
from .models.user_template_instance import user_template_instance
from .models.zero_off import zero_off
