from django.contrib import admin

from .models.Activities import Activities
from .models.ASOperation import ASOperation
from .models.ArchivedContacts import ArchivedContacts
from .models.ArchivedMediaFile import ArchivedMediaFile
from .models.ArchivedMediaFolder import ArchivedMediaFolder
from .models.ArchivedMediaInFolder import ArchivedMediaInFolder
from .models.ArchivedMediaLayoutPreset import ArchivedMediaLayoutPreset
from .models.ArchivedMediaTag import ArchivedMediaTag
from .models.ArchivedPost import ArchivedPost
from .models.ArchivedPostMedia import ArchivedPostMedia
from .models.ArchivedSetDetail import ArchivedSetDetail
from .models.ArchivedSetLog import ArchivedSetLog
from .models.ArchivedTag import ArchivedTag
from .models.ArchivedTrainingDetail import ArchivedTrainingDetail
from .models.ArchivedUserPreferences import ArchivedUserPreferences
from .models.ArchivedUserProfile import ArchivedUserProfile
from .models.Autosteer import Autosteer
from .models.BoatDetail import BoatDetail
from .models.BoatDriver import BoatDriver
from .models.BoatInfo import BoatInfo 
from .models.Call import Call
from .models.Comment import Comment
from .models.ConflictLog import ConflictLog
from .models.Contacts import Contacts
from .models.CourseSet import CourseSet
from .models.CourseSurveyData import CourseSurveyData
from .models.DeviceSyncStatus import DeviceSyncStatus
from .models.DriverInfo import DriverInfo
from .models.EquipmentSetup import EquipmentSetup
from .models.FileFormat import FileFormat
from .models.Follow import Follow
from .models.GpsCourse import GpsCourse
from .models.GpsSource import GpsSource
from .models.GroupInvite import GroupInvite
from .models.Hashtag import Hashtag
from .models.Health import Health
from .models.InputValidate import InputValidate
from .models.Location import Location
from .models.Log import Log
from .models.MeasurementUnits import MeasurementUnits
from .models.MediaFile import MediaFile
from .models.MediaFolder import MediaFolder
from .models.MediaInFolder import MediaInFolder
from .models.MediaLayoutPreset import MediaLayoutPreset
from .models.MediaTag import MediaTag
from .models.Metrics import Metrics
from .models.MobileDetail import MobileDetail
from .models.MobilePermissionProfile import MobilePermissionProfile
from .models.MobileTemplate import MobileTemplate
from .models.Notification import Notification
from .models.OnboardingEvent import OnboardingEvent
from .models.Post import Post
from .models.PostHashtag import PostHashtag
from .models.PostMedia import PostMedia
from .models.ProductCat import ProductCat
from .models.ProductInfo import ProductInfo
from .models.Reaction import Reaction
from .models.SetDetail import SetDetail
from .models.SetLog import SetLog
from .models.ShareLink import ShareLink
from .models.SharedSet import SharedSet
from .models.SharedSetDetail import SharedSetDetail
from .models.SkiGroup import SkiGroup
from .models.UserPreferences import UserPreferences
from .models.Stream import Stream
from .models.SyncQueue import SyncQueue
from .models.Tag import Tag
from .models.TemplateElement import TemplateElement
from .models.TrainingDetail import TrainingDetail
from .models.UIEventLog import UIEventLog
from .models.UISettings import UISettings
from .models.UserTemplateInstance import UserTemplateInstance