from django.db import models
from .file_format import file_format

class stream(models.Model):
    format = models.ForeignKey(file_format, on_delete=models.CASCADE)
    index = models.IntegerField()
    codec_name = models.CharField(max_length=50)
    codec_long_name = models.CharField(max_length=255)
    profile = models.CharField(max_length=50, null=True, blank=True)
    codec_type = models.CharField(max_length=20)
    codec_tag_string = models.CharField(max_length=10)
    codec_tag = models.CharField(max_length=20)
    width = models.IntegerField(null=True, blank=True)
    height = models.IntegerField(null=True, blank=True)
    coded_width = models.IntegerField(null=True, blank=True)
    coded_height = models.IntegerField(null=True, blank=True)
    pix_fmt = models.CharField(max_length=50, null=True, blank=True)
    level = models.IntegerField(null=True, blank=True)
    color_range = models.CharField(max_length=50, null=True, blank=True)
    color_space = models.CharField(max_length=50, null=True, blank=True)
    color_transfer = models.CharField(max_length=50, null=True, blank=True)
    color_primaries = models.CharField(max_length=50, null=True, blank=True)
    field_order = models.CharField(max_length=20, null=True, blank=True)
    refs = models.IntegerField(null=True, blank=True)
    r_frame_rate = models.CharField(max_length=20)
    avg_frame_rate = models.CharField(max_length=20)
    time_base = models.CharField(max_length=20)
    start_pts = models.BigIntegerField(null=True, blank=True)
    start_time = models.FloatField()
    duration_ts = models.BigIntegerField(null=True, blank=True)
    duration = models.FloatField()
    bit_rate = models.BigIntegerField(null=True, blank=True)
    nb_frames = models.IntegerField(null=True, blank=True)
    extradata_size = models.IntegerField(null=True, blank=True)

    # Stream Tags
    creation_time = models.DateTimeField(null=True, blank=True)
    language = models.CharField(max_length=10, null=True, blank=True)
    handler_name = models.CharField(max_length=100, null=True, blank=True)
    vendor_id = models.CharField(max_length=20, null=True, blank=True)

    # Dispositions
    disposition_default = models.BooleanField(default=False)
    disposition_dub = models.BooleanField(default=False)
    disposition_original = models.BooleanField(default=False)
    disposition_comment = models.BooleanField(default=False)
    disposition_lyrics = models.BooleanField(default=False)
    disposition_karaoke = models.BooleanField(default=False)
    disposition_forced = models.BooleanField(default=False)
    disposition_hearing_impaired = models.BooleanField(default=False)
    disposition_visual_impaired = models.BooleanField(default=False)
    disposition_clean_effects = models.BooleanField(default=False)
    disposition_attached_pic = models.BooleanField(default=False)
    disposition_timed_thumbnails = models.BooleanField(default=False)
    disposition_captions = models.BooleanField(default=False)
    disposition_descriptions = models.BooleanField(default=False)
    disposition_metadata = models.BooleanField(default=False)
    disposition_dependent = models.BooleanField(default=False)
    disposition_still_image = models.BooleanField(default=False)
